import requests
         

access_token = 'eyJraWQiOiIxNzhlZDM3NTVjY2U0YWEzODg5MTY5N2YyNjFlMGUzZCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJ0aXNtaXRoK2FwaUBleHRyZW1lbmV0d29ya3MuY29tIiwic2NvcGVzIjpbImxvZ291dCIsImF1dGgiLCJhdXRoOnIiLCJ0b2tlbjpuZXciLCJwZXJtOmNoZWNrIiwibHJvIiwibHJvOnIiLCJhY2NvdW50IiwiYWNjb3VudDpzd2l0Y2giLCJhY2NvdW50OnIiLCJ2aXE6YmFja3VwIiwidXNlciIsInVzZXItbWU6ciIsInVzZXI6ciIsImhpcSIsImhpcTpyIiwib3JnIiwib3JnOm5ldyIsIm9yZzpkZWwiLCJvcmc6cmVuYW1lIiwiaGlxLmN0eCIsImhpcS5jdHg6ciIsImhpcS5jdHg6dyIsImRldmljZSIsImRldmljZTpyIiwiZGV2aWNlOmxpc3QiLCJkZXZpY2U6dmlldyIsImRldmljZTpuZXciLCJkZXZpY2U6ZGVsIiwiZGV2aWNlOmNsaSIsImRldmljZTpkZXBsb3kiLCJkZXZpY2U6bWFuYWdlIiwiZGV2aWNlOnVubWFuYWdlIiwiZGV2aWNlOnJlYm9vdCIsImRldmljZTpyZXNldCIsImRldmljZTp0aHJlYWQtY29tbWlzc2lvbmVyIiwiY2xpZW50IiwiY2xpZW50OnIiLCJsb2NhdGlvbnMiLCJsb2NhdGlvbnM6ciIsIm5ldHdvcmstcG9saWN5IiwicG9saWN5OnNzaWQiLCJuZXR3b3JrLXBvbGljeTpyIiwibmV0d29yay1zY29yZWNhcmQiLCJuZXR3b3JrLXNjb3JlY2FyZDpyIiwic3NpZCIsInNzaWQ6ciIsInBjZzprZXkiLCJwY2c6a2V5OnIiLCJzdWJzY3JpcHRpb25zLXdlYmhvb2siLCJzdWJzY3JpcHRpb25zLXdlYmhvb2s6ciIsImNjZyIsImNjZzpyIiwibG9nIiwibG9nOnIiLCJjd3AiLCJjd3A6ciIsInNtcy10bXBsIiwic21zLXRtcGw6ciIsImNsYXNzLXJ1bGUiLCJjbGFzcy1ydWxlOnIiLCJ1c2VyLXByb2ZpbGUiLCJ1c2VyLXByb2ZpbGU6ciIsInR1bm5lbC1jb25jZW50cmF0b3IiLCJ0dW5uZWwtY29uY2VudHJhdG9yOnIiLCJyYWRpdXMtcHJveHkiLCJyYWRpdXMtcHJveHk6ciIsInJhZGl1cy1zZXJ2ZXIiLCJyYWRpdXMtc2VydmVyOnIiLCJ1c2VyZ3JvdXAiLCJ1c2VyZ3JvdXA6ciIsImRlcGxveW1lbnQiLCJkZXBsb3ltZW50OnIiLCJhZC1zZXJ2ZXIiLCJhZC1zZXJ2ZXI6ciIsImFsZXJ0IiwiYWxlcnQ6ciIsImFsZXJ0LXBvbGljaWVzIiwiYWxlcnQtcG9saWNpZXM6ciIsImFsZXJ0LXN1YnNjcmlwdGlvbnMiLCJhbGVydC1zdWJzY3JpcHRpb25zOnIiLCJhcHAiLCJhcHBsaWNhdGlvbjpyIiwibDMtYWRkcmVzcy1wcm9maWxlIiwibDMtYWRkcmVzcy1wcm9maWxlOnIiLCJ2bGFuLXByb2ZpbGUiLCJ2bGFuLXByb2ZpbGU6ciIsImVuZHVzZXIiLCJlbmR1c2VyOnIiLCJyYWRpdXMtY2xpZW50LW9iamVjdCIsInJhZGl1cy1jbGllbnQtb2JqZWN0OnIiLCJsZGFwLXNlcnZlciIsImxkYXAtc2VydmVyOnIiLCJlbWFpbC10ZW1wbGF0ZSIsImVtYWlsLXRlbXBsYXRlOnIiLCJjZXJ0aWZpY2F0ZSIsImNlcnRpZmljYXRlOnIiLCJyYWRpby1wcm9maWxlIiwicmFkaW8tcHJvZmlsZTpyIiwiaW90LXByb2ZpbGUiLCJpb3QtcHJvZmlsZTpyIiwiY2xpZW50LW1vbml0b3ItcHJvZmlsZSIsImNsaWVudC1tb25pdG9yLXByb2ZpbGU6ciIsImNvcGlsb3QtY29ubmVjdGl2aXR5LXdpcmVkOnIiLCJjb3BpbG90LWNvbm5lY3Rpdml0eS13aXJlbGVzczpyIiwiY29waWxvdC1hbm9tYWxpZXM6ciIsImxpY2Vuc2VzIiwibGljZW5zZXM6ciIsImNvcGlsb3QtYXNzdXJhbmNlLXNjYW5zOnIiLCJwYWNrZXQtY2FwdHVyZSIsInBhY2tldC1jYXB0dXJlOnIiLCJjb3VudHJ5IiwiY291bnRyeTpyIiwiY2FzIiwiY2FzOnIiLCJjYXMtcG9saWNpZXMiLCJjYXMtcG9saWNpZXM6ciIsImNhcy1tZXRhZGF0YTpyIiwiY25zLXN1YnNjcmlwdGlvbnMiLCJjbnMtc3Vic2NyaXB0aW9uczpyIl0sInVzZXJfaWQiOjIxNzkyMzIxLCJyb2xlIjoiQWRtaW5pc3RyYXRvciIsImN1c3RvbWVyX2lkIjo0OTYzMDcwMSwiY3VzdG9tZXJfbW9kZSI6MCwiaGlxX2VuYWJsZWQiOmZhbHNlLCJvd25lcl9pZCI6MjQ2NzgxLCJvcmdfaWQiOjAsImRhdGFfY2VudGVyIjoiQVBBQ19Ub2t5byIsInNoYXJkIjoiVVMiLCJob21lU2hhcmQiOiJVUyIsImhvbWVDdXN0b21lcklkIjoyMTc5MTk3MSwianRpIjoiMmM5ODJhYjFkOWJmNGI4ZTllNGE1MTA1YzY1ZWM5NTMiLCJpc3MiOiJodHRwczovL3VzMC5leHRyZW1lY2xvdWRpcS5jb20iLCJpYXQiOjE3MzQzNzQ0MzMsImV4cCI6MTc0MjE1MDI1MH0.DMOlZgpG9gUd1dDsG4hJOWVcyCuE3LWNF4FkhuuFE4i_Z6aFGVsVXP54ZGBRKa_PfoPdNLQVwOaIVeI7O_vYpZec8D3G42_6myIw3U5arx6CZfq5f0knKPyS_vknNBsjW8uGiWhgTXhI_JtQIzITcKtGCE8tbsVS5gvNV0MA6nfMbFJzPB0Brh_Zx6SgUhaTNYeVCzHz-lD4kt4gN2dfqZl2BAJPm2kE0QlATYZb3IbcChiyPehHkpTZ2q94ENLiy8cpiHx87_sLOe19knLbs_UuHcEWNG_FQywyaO1ydt__n8wb9ipbnK5KEqgFZWcPjYQomzfFSvLqXWfsyrKkKg'

url = f"https://api.extremecloudiq.com/account/viq/import"
headers = {'Authorization': f'Bearer {access_token}'}
params = {}

# timeoutInSeconds: 1800 (disabled)
# excludeDeviceFirmware: false (disabled)

response = requests.post(url, headers=headers, params=params)

print("Status Code:", response.status_code)

content_type = response.headers.get('Content-Type')
lro_url = response.headers.get('Location')
if lro_url:
    print(lro_url)
elif content_type and 'application/json' in content_type:
    try:
        print("Response Body:", response.json())
    except ValueError:
        print("Response is not valid JSON")
else:
    print("Content-Type is not application/json")
    print(response.text)
